//This imports the Metadata type from Next.js. It's used to define SEO-related 
// metadata like page title and description.
import type { Metadata } from "next";
import "./globals.css";
import Menu from "./Menu";
import BottomMenu from "./BottomMenu";




// This metadata is picked up by Next.js and automatically injected into the <head> tag of your HTML. 
// It's useful for: SEO, Browser tab title, Social sharing previews
// You can override or extend this metadata at the page level too.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="flex-row">

      <div className="flex w-full min-h-screen">
        <div className="bg-gradient-to-l from-gray-700 to-gray-800 flex-1"></div>

        <div className="bg-gray-700 flex flex-col w-7xl p-4">
          <Menu />
          {children}
          <BottomMenu />
        </div>

        <div className="bg-gradient-to-r from-gray-700 to-gray-800 flex-1"></div>
</div>


      </body>
    </html>
  );
}

